# numpy 

In [3]:
import numpy as np

a = np.array([1, 2 ,3])
b = np.array([2, 3, 4])

print(a + b)
print(a - b)
print(a * 4)
print(a * b)
print(a.dot(b))
print(sum(a*b)) # 내적 (각각의 값을 곱해서 다 더한다)

# ones는 1로 채워진 array를 만드는 것
c = np.ones([3, 4])
print(c)

# zeros는 0으로 채워진 array를 만드는 것
d = np.zeros([2, 5])
print(d)



[3 5 7]
[-1 -1 -1]
[ 4  8 12]
[ 2  6 12]
20
20
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[3, 2, 1], [1, 2, 3]])

print(A+B)
print(A-B)
print(A*B)  #원소곱
print(B.T)  # 전치
print(A.dot(B.T)) #행렬곱

[[4 4 4]
 [5 7 9]]
[[-2  0  2]
 [ 3  3  3]]
[[ 3  4  3]
 [ 4 10 18]]
[[3 1]
 [2 2]
 [1 3]]
[[10 14]
 [28 32]]


# 벡터 (vector)

In [5]:
class Vector :

    # *이 있으면 튜플의 형태로 들어간다 -> 리스트는 벡터가 아니기 때문에 사용
    def __init__(self, *lst):
        self.data = lst


    def __str__(self):
        return str(self.data)   # f"Vec{self.data}"도 가능


    # 이렇게 구현을 했지만 __add__를 쓰는게 좋음
    def add(self, other):
        # 값들을 더해서 새로운 리스트를 만듬
        tmp = [a + b for a, b in zip(self.data, other.data)]
        # 위에서 만든 리스트를 백터로 리턴
        # *을 하지 않으면 Vector([ ,  , ]) 이렇게 들어감. 우리는 그냥 Vector( , , ) 이 필요하므로 * 적용
        return Vector(*tmp)

        # == return Vector(*[a+b for a, b in zip(self.data, other.data)]) 이렇게 한 번에 써도 됨

    def __add__(self, other):
        return Vector(*[a+b for a, b in zip(self.data, other.data)])

    def __sub__(self, other):
        return Vector(*[a-b for a, b in zip(self.data, other.data)])

    
    def __mul__(self, other):
        # 벡터 * 벡터 면 내적한다.
        if type(other) == Vector:
            return sum(a * b for a, b in zip(self.data, other.data))
        # 벡터 * 숫자인 경우 곱한다. 
        else:
            return Vector(*[a * other for a in self.data])


    # 숫자 * 벡터의 경우 (순서가 다를경우)
    def __rmul__(self, other):
        return Vector(*[a * other for a in self.data])



a = Vector(1, 2, 3)
b = Vector(2, 3, 4)

c = a + b
d = b - a
e = b * 4
f = 3 * b
g = a * b

print(a, b, c, d, e, f, g)

(1, 2, 3) (2, 3, 4) (3, 5, 7) (1, 1, 1) (8, 12, 16) (6, 9, 12) 20


In [7]:
v1 = Vector(1,2,3)
v2 = Vector(3,1,5)

sum_of_squares = v1 * v1
length = (v1 * v1) ** 0.5 # 벡터의 크기 -> 제곱에 루트 씌우기
distance = ((v1 - v2) * (v1 - v2)) ** 0.5 # 두 벡터사이의 거리

print(sum_of_squares)
print(length)
print(distance)

14
3.7416573867739413
3.0


# 행렬 (matrix)

In [8]:
import numpy as np

A = np.array([[1,2,3], [2,3,4]])
B = np.array([[2,3,4], [3,4,5]])

print(A)
print(B)

[[1 2 3]
 [2 3 4]]
[[2 3 4]
 [3 4 5]]
