#  텐서 Tensor 만들기

In [ ]:
import torch

# tensor 만들어 보기
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float)
print("x =", x)
print("y =", y)

print(x.type()) #float 이 출력됨

# tensor 의 모양 알아보기. 몇 행 몇 열
print(x.shape) #size 보다 shape을 많이쓴다. 둘 다 동일
print(x.size())

# rank 알아보기 (차원)
print(len(x.shape))
# 아래 둘은 같음
print(x.ndimension())
print(x.ndim) # 많이 씀

x = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
y = tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.LongTensor
torch.Size([3, 3])
torch.Size([3, 3])
2
2
2


# 텐서 모양 바꾸기

In [ ]:
# 텐서 모양 바꾸기
# - unsqueeze(x, i): tensor x에 i 번째 차원 추가, 차원을 늘림

# 같은 값을 가지지만 모양이 다른 애를 만들때 사용

x0 = torch.unsqueeze(x, 0) # 0번째에 차원 추가
x1 = torch.unsqueeze(x, 1) # 1번째에 차원 추가
x2 = torch.unsqueeze(x, 2) # 2번째에 차원 추가

print(x0)
print(x0.shape)
print(x1)
print(x1.shape)
print(x2)
print(x2.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
torch.Size([3, 1, 3])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
torch.Size([3, 3, 1])


In [ ]:
# 텐서 모양 바꾸기
# - squeeze(x): 텐서 x에서 크기가 1인 차원 제거
 
print(x0)
print(x0.shape)

x00 = torch.squeeze(x0) # 1이 포함된 차원 제거
print(x00)
print(x00.shape)

x02 = torch.unsqueeze(x0, 2)
print(x02)
print(x02.shape)

x01 = torch.squeeze(x02) # 1이 포함된 차원 모두 제거
print(x01)
print(x01.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
tensor([[[[1, 2, 3]],

         [[4, 5, 6]],

         [[7, 8, 9]]]])
torch.Size([1, 3, 1, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [ ]:
# 유연하게 모양을 바꿈 
# - x.view([shape]): x를 [shape]의 모양으로 변환

print(x)

xView9 = x.view(9) # view()안의 값은 사이즈를 잘 보고 (알맞게) 넣어야함

print(xView9)
print(xView9.shape)

# 몇 개인지는 모르겠지만 한 줄로 쭉 보여주고 싶다 -> -1 사용 (데이터의 모양을 정확히 알지 못할때)
xV = x.view(-1)
print(xV)

# 마지막꺼는 알아서 채워줬으면 좋겠다 하면 마지막에 -1
xV2 = x.view(1, 3, -1) #-1을 두 군데에 쓸 수는 없음
print(xV2)

# 기존 x 와 동일
xV3 = x.view(3, 3 )
print(xV3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


# 행렬 연산

In [ ]:
# xw + b
 
x = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float)

# randn - 평균이 0 이고, 표준편차가 1인 랜덤 값을 채워줌
w = torch.randn(1, 2 ,dtype=torch.float)
b = torch.randn(3, 1, dtype=torch.float)

print(x)
print(w)
print(w.type())
print(b)


# x * w + b
# mm = matmul
# .T 는 transpose
xwp = torch.mm(x, w.T) + b

print(xwp)
# axis -> 차원, view 로 모양 맞춰줌
print((x*w).sum(axis = 1).view(3, 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[-0.1527,  0.9265]])
torch.FloatTensor
tensor([[ 0.4697],
        [-1.1260],
        [ 0.7457]])
tensor([[2.1700],
        [2.1220],
        [5.5413]])
tensor([[1.7003],
        [3.2479],
        [4.7956]])


# 기울기 계산

In [ ]:
#  Autograd: 기울기 계산
# - requires_grad 값이 설정된 tensor에 대해서, pytorch는 자동으로 기울기를 계산해 줌

# requires_grad를 설정해야 기울기 계산해줌
w = torch.tensor(1.0, requires_grad = True) # 1.0에서의 기울기 2.0을 넣으면 36. 이 나옴
a = 3 * w
l = a** 2
l.backward() # 기울기 계산 하자 !
print('l을 w로 미분한 값은: ', w.grad) 

l을 w로 미분한 값은:  tensor(18.)


#  Linear Regression - 학습 데이터 생성

In [16]:
# y = 2x1 + 3x2 - 4 찾기

import torch

x_train = torch.tensor([[1,2], [3,2], [3,7], [1,1], [1,0]], dtype=torch.float)
# 실제값 y
y_train = torch.tensor([[4], [8], [23], [1], [-2]], dtype=torch.float)

# W, b 초기화, 기본적으로 zeros는 float타입
W = torch.zeros(2, 1)
b = torch.zeros(1)

print(W)
print(b)

lr = 0.01 #learning rate

for epoch in range(1000):

  # W, b 값을 반복해서 업데이트
  W.requires_grad_(True)
  b.requires_grad_(True)

  # 가설 Hypothesis H(x) = wx + b
  h = torch.mm(x_train, W) + b
  cost = torch.mean((h - y_train) ** 2) # mse <-> 루트까지 씌우면 rmse=torch.mean((h - y) ** 2) ** 0.5 

  # cost에 대해서 미분 실행하여 기울기 구함
  cost.backward()

  with torch.no_grad(): # 기울기에 전혀 영향을 미치지 않음
    W = W - lr * W.grad # 기울기에 lr 곱한 만큼 이동해서 값을 업데이트
    b = b - lr * b.grad

    if epoch % 100 == 0:
      print(f"W: {W}, b: {b}, cost: {cost}")
    


tensor([[0.],
        [0.]])
tensor([0.])
W: tensor([[0.3840],
        [0.7440]]), b: tensor([0.1360]), cost: 122.80000305175781
W: tensor([[0.6226],
        [3.1603]]), b: tensor([-1.3651]), cost: 1.5337574481964111
W: tensor([[0.9143],
        [3.1864]]), b: tensor([-2.1790]), cost: 0.7582405805587769
W: tensor([[1.2106],
        [3.1417]]), b: tensor([-2.7023]), cost: 0.38928839564323425
W: tensor([[1.4328],
        [3.1025]]), b: tensor([-3.0705]), cost: 0.20005758106708527
W: tensor([[1.5932],
        [3.0736]]), b: tensor([-3.3338]), cost: 0.10281281173229218
W: tensor([[1.7084],
        [3.0528]]), b: tensor([-3.5224]), cost: 0.05283750221133232
W: tensor([[1.7909],
        [3.0378]]), b: tensor([-3.6576]), cost: 0.027154315263032913
W: tensor([[1.8501],
        [3.0271]]), b: tensor([-3.7546]), cost: 0.01395510695874691
W: tensor([[1.8926],
        [3.0194]]), b: tensor([-3.8241]), cost: 0.007171782664954662


In [17]:
# 학습이 잘 되는지 확인하기위한 내용 출력
 
x_test = torch.tensor([[5, 10]], dtype=torch.float )
test_result = torch.mm(x_test, W) + b

print(test_result)

tensor([[35.8800]])


# LinearRegression with Scikit-learn
 

In [18]:
from sklearn.linear_model import LinearRegression

x = [[1,2], [3,2], [3,7], [1,1], [1,0]]
y = [[4], [8], [23], [1], [-2]]

model = LinearRegression()
model.fit(x, y)

LinearRegression()

In [20]:
#학습 결과 (Parameter) 확인
# coef_: 기울기 값 (W에 해당)
# intercept_: y절편 값 (b에 해당)

print(model.coef_, model.intercept_)

[[2. 3.]] [-4.]


In [22]:
# y 값 예측하기
print(model.predict([[5,10]])) 

[[36.]]
